demo-mysql:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=admin
    - MYSQL_DATABASE=world
    - MYSQL_USER=root
    - MYSQL_PASSWORD=admin

spring-boot-jpa-docker-webapp:
  image: champ45/spring-boot-jpa-docker-webapp
  links:
    - demo-mysql:mysql
  ports:
    - 9090:9090
