spring:
  datasource:
    url: jdbc:mysql://159.203.220.71:3306/world
    username: root
    password: admin
    platform: mysql
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://159.203.220.71:3306/world
    username: root
    password: admin
    initialize: true
